# Generated by Django 5.0.4 on 2024-07-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.IntegerField()),
                ('patient_disease', models.CharField(max_length=100)),
                ('test_type', models.CharField(max_length=100)),
                ('test_date', models.DateField()),
                ('technician_name', models.CharField(max_length=100)),
            ],
        ),
    ]
