# Generated by Django 5.0.6 on 2024-06-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PatientRegistration',
            fields=[
                ('patient_id', models.CharField(editable=False, max_length=8, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField()),
                ('mobile', models.IntegerField(blank=True, max_length=10)),
                ('country', models.CharField(max_length=13)),
                ('state', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=13)),
                ('Address', models.TextField()),
                ('blood_group', models.CharField(max_length=10)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('issue', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('SURGERY', 'Surgery')], max_length=15)),
                ('previous_medical_history', models.TextField(verbose_name='medical history')),
            ],
        ),
    ]
