# Generated by Django 5.0.6 on 2024-06-24 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0002_delete_admissiondetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientregistration',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='patientregistration',
            old_name='issue',
            new_name='issue_type',
        ),
        migrations.CreateModel(
            name='AdmissionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('admission_reason', models.TextField(verbose_name='Reason For Admission')),
                ('admission_date', models.DateField(verbose_name='Date of Admission')),
                ('discharge_date', models.DateField(blank=True, null=True, verbose_name='Date of Discharge')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.patientregistration')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
