# Generated by Django 5.0.4 on 2024-06-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='certifications',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='experience',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='nurse_pics/'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='shift',
            field=models.CharField(max_length=50),
        ),
    ]
